#!/bin/bash -eux

# Send the log output from this script to custom-data.log
exec 2> >(sudo tee -a /var/log/custom-data.log)

sudo echo '${consul_config}' > /etc/consul.d/config/config.json
sudo echo '${vault_config}' > /etc/vault.d/config/default.hcl

sudo chown consul:consul /etc/consul.d/config/config.json
sudo chown vault:vault /etc/vault.d/config/default.hcl

systemctl daemon-reload
systemctl start consul.service
systemctl enable consul.service

systemctl start vault.service
systemctl enable vault.service