#!/bin/bash -eux

# Send the log output from this script to custom-data.log
exec 2> >(sudo tee -a /var/log/custom-data.log)

sudo echo '${consul_config}' > /etc/consul.d/config/config.json
sudo echo '${vault_config}' > /etc/vault.d/config/default.hcl

sudo chown consul:consul /etc/consul.d/config/config.json
sudo chown vault:vault /etc/vault.d/config/default.hcl

sudo systemctl daemon-reload
sudo systemctl start consul.service
sudo systemctl enable consul.service

sudo systemctl start vault.service
sudo systemctl enable vault.service